set dev env
edchainio/client-gui pull request #36
Opened 2017-12-05 20:42 UTC by SeanXiaohengMao

2017-12-05 20:44 UTC, devarshjoshi requested changes
can you please make this for the child window too ?

2017-12-10 23:35 UTC, SeanXiaohengMao commented
I made this tiny modification on the new version of code.

2017-12-11 19:13 UTC, devarshjoshi approved these changes

2017-12-11 19:13 UTC, merged

2017-12-11 19:13 UTC, devarshjoshi commented
thank you.